// Domain types shared across the app.

// ─── Ingredient entries ──────────────────────────────────────────────────────

/** A single ingredient the user has entered, with a required/optional toggle. */
export interface IngredientEntry {
  id: string;
  text: string;
  /** If true, the recipe must contain this ingredient to appear in results. */
  required: boolean;
}

// ─── Recipe sources ─────────────────────────────────────────────────────────

/** A single entry in a source's lightweight URL index. */
export interface IndexEntry {
  title: string;
  url: string;
}

/** Precomputed token sets for one ingredient line — `all` for general match
 *  scoring, `strict` (notes/alternatives stripped) for required-ingredient
 *  matching. See `shared/tokens.js`. */
export interface IngredientTokens {
  all: string[];
  strict: string[];
}

/** A single enriched recipe, stored in the `recipes` IndexedDB store keyed by `[sourceId, url]`. */
export interface RecipeRecord {
  sourceId: string;
  url: string;
  title: string;
  ingredients: string[];
  cuisine: string | null;
  mealType: string | null;
  totalTime: string | null;
  /** Parsed cooking time in minutes, for filtering. Null if not available. */
  totalTimeMinutes: number | null;
  servings: string | null;
  image: string | null;
  /** Number of instruction steps, used as a complexity proxy. */
  instructionCount: number;
  /** Precomputed tokens, one entry per `ingredients` line. Absent on records
   *  enriched before Session 2 until they're lazily migrated on first search. */
  tokens?: IngredientTokens[];
}

/** A recipe website the user has added — lightweight metadata only. Full recipe
 *  data lives in the `recipes` IndexedDB store, keyed by source id. */
export interface SourceMeta {
  id: string;
  name: string;
  url: string;
  emoji: string;
  active: boolean;
  /** Lightweight URL+title index (all recipes found by indexing), or null if not yet indexed. */
  index: IndexEntry[] | null;
  indexedAt: string | null;
  indexCount: number;
  enrichedCount: number;
  enrichedAt: string | null;
  /** True for sources shipped as prebuilt data rather than added by the user. */
  builtin?: boolean;
  /** True if the user has hidden this (built-in) source from the Sources list. Implies inactive. */
  hidden?: boolean;
}

// ─── Search filters ──────────────────────────────────────────────────────────

/** Max cooking time in minutes, "unknown" for recipes with no time data, or "any" for no filter. */
export type TimeFilter = "any" | "30" | "60" | "120" | "unknown";

/** Complexity based on instruction step count. */
export type ComplexityFilter = "any" | "simple" | "moderate" | "complex" | "unknown";

/** Meal type label, "unknown" for recipes with no meal type, or "any" for no filter. */
export type MealTypeFilter = string; // "any" | "unknown" | specific label

// ─── Search results ──────────────────────────────────────────────────────────

/** A local search result computed from the enriched index. */
export interface SearchResult {
  title: string;
  source: string;
  sourceEmoji: string;
  sourceUrl: string;
  cuisine: string | null;
  mealType: string | null;
  totalTime: string | null;
  totalTimeMinutes: number | null;
  servings: string | null;
  image: string | null;
  matchScore: number;
  instructionCount: number;
  missingIngredients: string[];
  ingredientsRaw: string[];
}

// ─── UI types ────────────────────────────────────────────────────────────────

export type Tab = "search" | "sources" | "cupboard";

// ─── Prebuilt data pipeline (data/manifest.json, generated by scripts/build-index.mjs) ──

export interface ManifestSourceEntry {
  id: string;
  name: string;
  url: string;
  emoji: string;
  count: number;
  file: string;
  updated_at: string;
}

export interface Manifest {
  generated_at: string | null;
  sources: ManifestSourceEntry[];
}

// ─── API responses (mirror what the Worker routes return) ────────────────────

export interface IndexSourceResponse {
  source: string;
  recipes: IndexEntry[];
  count: number;
  indexed_at: string;
}

export interface FetchRecipeResponse {
  url: string;
  title: string;
  description: string | null;
  image: string | null;
  totalTime: string | null;
  prepTime: string | null;
  cookTime: string | null;
  servings: string | null;
  cuisine: string | null;
  category: string | null;
  keywords: string | null;
  ingredients: string[];
  instructions: string[];
  nutrition: {
    calories: string | null;
    protein: string | null;
    fat: string | null;
    carbs: string | null;
  } | null;
  author: string | null;
}
